version: "3.3"
services:
  ffmpeg-recorder:
    build: .
    pull_policy: build
    container_name: ffmpeg-recorder

    volumes:
      - /mnt/nfs/fast-dockers/willow-recordings:/recordings
    restart: unless-stopped
