version: "3.3"
services:
  ffmpeg-recorder:
    build: .
    pull_policy: build
    container_name: ffmpeg-recorder
    environment:
      - SNAPSHOT_URL=$SNAPSHOT_URL
      - FPS=$FPS
      - CLIP_LENGTH=$CLIP_LENGTH
      - RETENTION_DAYS=$RETENTION_DAYS
      - TZ=$TZ
      - QUALITY=$QUALITY
    volumes:
      - $RECORDINGS_VOLUME:/recordings
    restart: unless-stopped
