version: "3.3"
services:
  ffmpeg-recorder:
    build: .
    pull_policy: build
    container_name: ffmpeg-recorder
    environment:
      - SNAPSHOT_URL=http://snapshot_url
      - FPS=24
      - CLIP_LENGTH=60
      - RETENTION_DAYS=7
      - TZ=Europe/Brussels
    volumes:
      - volume_to_save_recordings:/recordings
    restart: unless-stopped
